language: objective-c
os: osx
osx_image: xcode7.1
xcode_workspace: Kingfisher.xcworkspace
xcode_scheme: Kingfisher

script: xcodebuild -workspace Kingfisher.xcworkspace -scheme Kingfisher -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
